"""initial schema

Revision ID: 403e80d4c7c9
Revises:
Create Date: 2026-08-23 08:53:29.445309
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "403e80d4c7c9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "type", sa.Enum(
                "NUMBERS",
                "GAMES",
                "SMM",
                "APPS",
                "BALANCES",
                "CARDS",
                "SUBSCRIPTIONS",
                "VERIFICATION",
                "CODES",
                "STORE",
                "CUSTOM",
                name="apiprovidertype",
            ), nullable=False
        ),
        sa.Column(
            "protocol_type",
            sa.Enum("SMS", "SMM_V2", "GAMES_GENERIC", "CUSTOM", name="apiprotocoltype"),
            nullable=False,
        ),
        sa.Column("api_url", sa.String(length=500), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("rate_to_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("low_balance_threshold", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("total_services", sa.Integer(), nullable=False),
        sa.Column("custom_config", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(length=64), nullable=False),
        sa.Column("emoji", sa.String(length=8), nullable=False),
        sa.Column(
            "type", sa.Enum(
                "NUMBERS",
                "SMM",
                "GAMES",
                "APPS",
                "BALANCES",
                "CARDS",
                "SUBSCRIPTIONS",
                "VERIFICATION",
                "CODES",
                "CUSTOM",
                name="categorytype",
            ), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("target_value", sa.Integer(), nullable=False),
        sa.Column("reward_points", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="challengestatus"), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_challenges_code"), "challenges", ["code"], unique=True)
    op.create_index(op.f("ix_challenges_status"), "challenges", ["status"], unique=False)
    op.create_table(
        "mandatory_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("username_or_link", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
    )
    op.create_table(
        "number_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name_ar", sa.String(length=64), nullable=False),
        sa.Column("emoji", sa.String(length=8), nullable=False),
        sa.Column("fivesim_code", sa.String(length=32), nullable=True),
        sa.Column("herosms_code", sa.String(length=32), nullable=True),
        sa.Column("sms_activate_code", sa.String(length=32), nullable=True),
        sa.Column("smshub_code", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_number_services_code"), "number_services", ["code"], unique=True)
    op.create_table(
        "provider_status",
        sa.Column(
            "provider",
            sa.Enum("FIVESIM", "HEROSMS", "SMS_ACTIVATE", "SMSHUB", name="providername"),
            nullable=False,
        ),
        sa.Column("balance", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("provider"),
    )
    op.create_table(
        "service_pricing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service", sa.String(length=64), nullable=False),
        sa.Column("country_code", sa.String(length=32), nullable=True),
        sa.Column(
            "provider",
            sa.Enum("FIVESIM", "HEROSMS", "SMS_ACTIVATE", "SMSHUB", name="providername"),
            nullable=True,
        ),
        sa.Column("margin_type", sa.String(length=16), nullable=False),
        sa.Column("margin_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "stars_packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stars_amount", sa.Integer(), nullable=False),
        sa.Column("usd_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("language_code", sa.String(length=8), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("referrer_id", sa.Integer(), nullable=True),
        sa.Column("is_activated", sa.Boolean(), nullable=False),
        sa.Column("referral_bonus_paid", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("total_spent_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_orders", sa.Integer(), nullable=False),
        sa.Column("cashback_earned_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("loyalty_points", sa.Integer(), nullable=False),
        sa.Column("loyalty_streak", sa.Integer(), nullable=False),
        sa.Column("last_checkin_date", sa.Date(), nullable=True),
        sa.Column(
            "joined_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_activity_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "abuse_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("details", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_abuse_events_created_at"), "abuse_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_abuse_events_event_type"), "abuse_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_abuse_events_user_id"), "abuse_events", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "DELETE",
                "ACTIVATE",
                "DEACTIVATE",
                "SYNC",
                "PRICE_CHANGE",
                "OTHER",
                name="auditaction",
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("entity_name", sa.String(length=255), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_admin_id"), "audit_logs", ["admin_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_table(
        "auto_invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("SHAMCASH_AUTO", "USDT_AUTO", name="autoinvoicemethod"),
            nullable=False,
        ),
        sa.Column("external_invoice_id", sa.String(length=128), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("amount_original", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("network", sa.String(length=16), nullable=True),
        sa.Column("payment_address", sa.String(length=255), nullable=True),
        sa.Column("qr_code_url", sa.String(length=500), nullable=True),
        sa.Column("payment_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "EXPIRED", "FAILED", "CANCELLED", name="autoinvoicestatus"),
            nullable=False,
        ),
        sa.Column("transaction_ref", sa.String(length=255), nullable=True),
        sa.Column("status_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("status_message_id", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("raw_data", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auto_invoices_external_invoice_id"),
        "auto_invoices",
        ["external_invoice_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_auto_invoices_transaction_ref"), "auto_invoices", ["transaction_ref"], unique=False
    )
    op.create_index(op.f("ix_auto_invoices_user_id"), "auto_invoices", ["user_id"], unique=False)
    op.create_table(
        "broadcast_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("total_sent", sa.Integer(), nullable=False),
        sa.Column("total_failed", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cashback_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("order_type", sa.String(length=32), nullable=False),
        sa.Column("order_amount_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cashback_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "order_id", "order_type", name="uq_cashback_order"),
    )
    op.create_index(op.f("ix_cashback_logs_user_id"), "cashback_logs", ["user_id"], unique=False)
    op.create_table(
        "challenge_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("challenge_id", "user_id", name="uq_challenge_user"),
    )
    op.create_index(
        op.f("ix_challenge_progress_challenge_id"),
        "challenge_progress",
        ["challenge_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_challenge_progress_user_id"), "challenge_progress", ["user_id"], unique=False
    )
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name_ar", sa.String(length=64), nullable=False),
        sa.Column("flag", sa.String(length=8), nullable=False),
        sa.Column("fivesim_code", sa.String(length=32), nullable=True),
        sa.Column("herosms_code", sa.String(length=16), nullable=True),
        sa.Column("sms_activate_code", sa.String(length=16), nullable=True),
        sa.Column("smshub_code", sa.String(length=16), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("added_by_admin_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["added_by_admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_countries_code"), "countries", ["code"], unique=True)
    op.create_table(
        "coupons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("discount_type", sa.String(length=16), nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("min_order_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_coupons_code"), "coupons", ["code"], unique=True)
    op.create_table(
        "deposit_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("proof_photo_file_id", sa.String(length=255), nullable=True),
        sa.Column("proof_tx_number", sa.String(length=255), nullable=True),
        sa.Column("payment_method", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="depositstatus"),
            nullable=False,
        ),
        sa.Column("admin_id", sa.Integer(), nullable=True),
        sa.Column("admin_chat_message_id", sa.BigInteger(), nullable=True),
        sa.Column("reject_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deposit_requests_proof_tx_number"),
        "deposit_requests",
        ["proof_tx_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deposit_requests_user_id"), "deposit_requests", ["user_id"], unique=False
    )
    op.create_table(
        "gift_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gift_codes_code"), "gift_codes", ["code"], unique=True)
    op.create_table(
        "loyalty_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("related_table", sa.String(length=64), nullable=True),
        sa.Column("related_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loyalty_events_created_at"), "loyalty_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_loyalty_events_event_key"), "loyalty_events", ["event_key"], unique=True
    )
    op.create_index(op.f("ix_loyalty_events_user_id"), "loyalty_events", ["user_id"], unique=False)
    op.create_table(
        "number_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("FIVESIM", "HEROSMS", "SMS_ACTIVATE", "SMSHUB", name="providername"),
            nullable=False,
        ),
        sa.Column("provider_order_id", sa.String(length=64), nullable=False),
        sa.Column("service", sa.String(length=64), nullable=False),
        sa.Column("country_code", sa.String(length=32), nullable=False),
        sa.Column("operator", sa.String(length=32), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("price_provider_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("price_sell_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CODE_RECEIVED",
                "COMPLETED",
                "EXPIRED",
                "CANCELLED",
                "REFUNDED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("sms_code", sa.String(length=64), nullable=True),
        sa.Column("full_sms_text", sa.Text(), nullable=True),
        sa.Column(
            "purchased_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("status_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("status_message_id", sa.BigInteger(), nullable=True),
        sa.Column("awaiting_extra_code", sa.Boolean(), nullable=False),
        sa.Column("extra_codes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_number_orders_user_id"), "number_orders", ["user_id"], unique=False)
    op.create_table(
        "product_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("normalized_title", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "IN_REVIEW", "FULFILLED", "REJECTED", name="productrequeststatus"),
            nullable=False,
        ),
        sa.Column("votes_count", sa.Integer(), nullable=False),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column("handled_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("handled_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["handled_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_requests_created_at"), "product_requests", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_requests_normalized_title"),
        "product_requests",
        ["normalized_title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_requests_status"), "product_requests", ["status"], unique=False
    )
    op.create_index(op.f("ix_product_requests_title"), "product_requests", ["title"], unique=False)
    op.create_index(
        op.f("ix_product_requests_user_id"), "product_requests", ["user_id"], unique=False
    )
    op.create_table(
        "provider_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_provider_id", sa.Integer(), nullable=False),
        sa.Column("external_service_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("service_type", sa.String(length=64), nullable=True),
        sa.Column("rate", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("rate_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "price_type",
            sa.Enum("PER_1000", "PER_ITEM", "FIXED", name="providerpricetype"),
            nullable=False,
        ),
        sa.Column("min_quantity", sa.Integer(), nullable=False),
        sa.Column("max_quantity", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requires_link", sa.Boolean(), nullable=False),
        sa.Column("requires_quantity", sa.Boolean(), nullable=False),
        sa.Column("requires_player_id", sa.Boolean(), nullable=False),
        sa.Column("supports_refill", sa.Boolean(), nullable=False),
        sa.Column("supports_cancel", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "DELETED_FROM_PROVIDER", name="providerservicestatus"),
            nullable=False,
        ),
        sa.Column("raw_data", sa.Text(), nullable=True),
        sa.Column(
            "last_updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_provider_id"],
            ["api_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_provider_id", "external_service_id", name="uq_provider_service"),
    )
    op.create_index(
        op.f("ix_provider_services_api_provider_id"),
        "provider_services",
        ["api_provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_services_category"), "provider_services", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_provider_services_external_service_id"),
        "provider_services",
        ["external_service_id"],
        unique=False,
    )
    op.create_table(
        "rate_limit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rate_limit_logs_user_id"), "rate_limit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "reseller_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("markup_percent", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reseller_accounts_user_id"), "reseller_accounts", ["user_id"], unique=True
    )
    op.create_table(
        "sub_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(length=64), nullable=False),
        sa.Column("emoji", sa.String(length=8), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("image_file_id", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sub_categories_category_id"), "sub_categories", ["category_id"], unique=False
    )
    op.create_table(
        "support_tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED", name="supportticketstatus"),
            nullable=False,
        ),
        sa.Column("admin_id", sa.Integer(), nullable=True),
        sa.Column("admin_reply", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_support_tickets_created_at"), "support_tickets", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_support_tickets_status"), "support_tickets", ["status"], unique=False)
    op.create_index(
        op.f("ix_support_tickets_user_id"), "support_tickets", ["user_id"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DEPOSIT",
                "PURCHASE",
                "REFUND",
                "REFERRAL_BONUS",
                "TRANSFER_IN",
                "TRANSFER_OUT",
                "ADMIN_ADD",
                "ADMIN_DEDUCT",
                "CASHBACK",
                "STARS_DEPOSIT",
                "COUPON_BONUS",
                "LOYALTY_REDEEM",
                "GIFT_REDEEM",
                name="transactiontype",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("related_table", sa.String(length=32), nullable=True),
        sa.Column("related_id", sa.Integer(), nullable=True),
        sa.Column("payment_reference", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_payment_reference"),
        "transactions",
        ["payment_reference"],
        unique=True,
    )
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_table(
        "transfers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_user_id", sa.Integer(), nullable=False),
        sa.Column("to_user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "coupon_usages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coupon_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("discount_applied", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "used_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["coupons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("coupon_id", "user_id", name="uq_coupon_user"),
    )
    op.create_index(
        op.f("ix_coupon_usages_coupon_id"), "coupon_usages", ["coupon_id"], unique=False
    )
    op.create_index(op.f("ix_coupon_usages_user_id"), "coupon_usages", ["user_id"], unique=False)
    op.create_table(
        "gift_redemptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gift_code_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "redeemed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["gift_code_id"], ["gift_codes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gift_code_id", "user_id", name="uq_gift_code_user"),
    )
    op.create_index(
        op.f("ix_gift_redemptions_gift_code_id"), "gift_redemptions", ["gift_code_id"], unique=False
    )
    op.create_index(
        op.f("ix_gift_redemptions_user_id"), "gift_redemptions", ["user_id"], unique=False
    )
    op.create_table(
        "product_request_votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["request_id"], ["product_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", "user_id", name="uq_product_request_vote"),
    )
    op.create_index(
        op.f("ix_product_request_votes_request_id"),
        "product_request_votes",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_request_votes_user_id"), "product_request_votes", ["user_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub_category_id", sa.Integer(), nullable=False),
        sa.Column("api_provider_id", sa.Integer(), nullable=True),
        sa.Column("provider_service_ref_id", sa.Integer(), nullable=True),
        sa.Column("provider_service_id", sa.String(length=64), nullable=True),
        sa.Column("name_ar", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("image_file_id", sa.String(length=255), nullable=True),
        sa.Column("price_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cost_price_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "pricing_type",
            sa.Enum("FIXED", "MARGIN_PERCENT", name="productpricingtype"),
            nullable=False,
        ),
        sa.Column("profit_margin_percent", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "display_type",
            sa.Enum("PER_1000", "PER_MIN_QUANTITY", "FIXED_TOTAL", name="productdisplaytype"),
            nullable=False,
        ),
        sa.Column("min_quantity", sa.Integer(), nullable=False),
        sa.Column("max_quantity", sa.Integer(), nullable=False),
        sa.Column("requires_player_id", sa.Boolean(), nullable=False),
        sa.Column("requires_link", sa.Boolean(), nullable=False),
        sa.Column("requires_quantity", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="productstatus"), nullable=False),
        sa.Column(
            "fulfillment_type",
            sa.Enum("API", "INVENTORY", "MANUAL", name="productfulfillmenttype"),
            nullable=False,
        ),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_bestseller", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("total_sold", sa.Integer(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_provider_id"],
            ["api_providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_service_ref_id"],
            ["provider_services.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_category_id"],
            ["sub_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_sub_category_id"), "products", ["sub_category_id"], unique=False
    )
    op.create_table(
        "reseller_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reseller_id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reseller_id"], ["reseller_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reseller_api_keys_key_hash"), "reseller_api_keys", ["key_hash"], unique=True
    )
    op.create_index(
        op.f("ix_reseller_api_keys_reseller_id"), "reseller_api_keys", ["reseller_id"], unique=False
    )
    op.create_table(
        "product_watches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("last_seen_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("last_seen_stock", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_notified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_id", name="uq_product_watch"),
    )
    op.create_index(
        op.f("ix_product_watches_product_id"), "product_watches", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_watches_user_id"), "product_watches", ["user_id"], unique=False
    )
    op.create_table(
        "promotions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "discount_type",
            sa.Enum("PERCENT", "FIXED", name="promotiondiscounttype"),
            nullable=False,
        ),
        sa.Column("discount_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promotions_is_active"), "promotions", ["is_active"], unique=False)
    op.create_index(op.f("ix_promotions_product_id"), "promotions", ["product_id"], unique=False)
    op.create_table(
        "user_favorites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_id", name="uq_user_product_favorite"),
    )
    op.create_index(
        op.f("ix_user_favorites_product_id"), "user_favorites", ["product_id"], unique=False
    )
    op.create_index(op.f("ix_user_favorites_user_id"), "user_favorites", ["user_id"], unique=False)
    op.create_table(
        "unified_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("api_provider_id", sa.Integer(), nullable=True),
        sa.Column("promotion_id", sa.Integer(), nullable=True),
        sa.Column("external_order_id", sa.String(length=64), nullable=True),
        sa.Column("target", sa.String(length=500), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cost_price_usd", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "REFUNDED",
                "PARTIAL",
                name="unifiedorderstatus",
            ),
            nullable=False,
        ),
        sa.Column("status_message", sa.String(length=500), nullable=True),
        sa.Column("result_data", sa.Text(), nullable=True),
        sa.Column("start_count", sa.Integer(), nullable=True),
        sa.Column("remains", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_provider_id"],
            ["api_providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["promotion_id"],
            ["promotions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_unified_orders_user_id"), "unified_orders", ["user_id"], unique=False)
    op.create_table(
        "digital_inventory_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("encrypted_value", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "RESERVED", "SOLD", "VOID", name="inventoryitemstatus"),
            nullable=False,
        ),
        sa.Column("unified_order_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sold_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["unified_order_id"],
            ["unified_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unified_order_id"),
    )
    op.create_index(
        op.f("ix_digital_inventory_items_product_id"),
        "digital_inventory_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_digital_inventory_items_status"),
        "digital_inventory_items",
        ["status"],
        unique=False,
    )
    op.create_table(
        "product_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("unified_order_id", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["unified_order_id"],
            ["unified_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_id", name="uq_product_review"),
    )
    op.create_index(
        op.f("ix_product_reviews_product_id"), "product_reviews", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_reviews_user_id"), "product_reviews", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_reviews_user_id"), table_name="product_reviews")
    op.drop_index(op.f("ix_product_reviews_product_id"), table_name="product_reviews")
    op.drop_table("product_reviews")
    op.drop_index(op.f("ix_digital_inventory_items_status"), table_name="digital_inventory_items")
    op.drop_index(
        op.f("ix_digital_inventory_items_product_id"), table_name="digital_inventory_items"
    )
    op.drop_table("digital_inventory_items")
    op.drop_index(op.f("ix_unified_orders_user_id"), table_name="unified_orders")
    op.drop_table("unified_orders")
    op.drop_index(op.f("ix_user_favorites_user_id"), table_name="user_favorites")
    op.drop_index(op.f("ix_user_favorites_product_id"), table_name="user_favorites")
    op.drop_table("user_favorites")
    op.drop_index(op.f("ix_promotions_product_id"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_is_active"), table_name="promotions")
    op.drop_table("promotions")
    op.drop_index(op.f("ix_product_watches_user_id"), table_name="product_watches")
    op.drop_index(op.f("ix_product_watches_product_id"), table_name="product_watches")
    op.drop_table("product_watches")
    op.drop_index(op.f("ix_reseller_api_keys_reseller_id"), table_name="reseller_api_keys")
    op.drop_index(op.f("ix_reseller_api_keys_key_hash"), table_name="reseller_api_keys")
    op.drop_table("reseller_api_keys")
    op.drop_index(op.f("ix_products_sub_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_product_request_votes_user_id"), table_name="product_request_votes")
    op.drop_index(op.f("ix_product_request_votes_request_id"), table_name="product_request_votes")
    op.drop_table("product_request_votes")
    op.drop_index(op.f("ix_gift_redemptions_user_id"), table_name="gift_redemptions")
    op.drop_index(op.f("ix_gift_redemptions_gift_code_id"), table_name="gift_redemptions")
    op.drop_table("gift_redemptions")
    op.drop_index(op.f("ix_coupon_usages_user_id"), table_name="coupon_usages")
    op.drop_index(op.f("ix_coupon_usages_coupon_id"), table_name="coupon_usages")
    op.drop_table("coupon_usages")
    op.drop_table("transfers")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_payment_reference"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_support_tickets_user_id"), table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_status"), table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_created_at"), table_name="support_tickets")
    op.drop_table("support_tickets")
    op.drop_index(op.f("ix_sub_categories_category_id"), table_name="sub_categories")
    op.drop_table("sub_categories")
    op.drop_index(op.f("ix_reseller_accounts_user_id"), table_name="reseller_accounts")
    op.drop_table("reseller_accounts")
    op.drop_index(op.f("ix_rate_limit_logs_user_id"), table_name="rate_limit_logs")
    op.drop_table("rate_limit_logs")
    op.drop_index(op.f("ix_provider_services_external_service_id"), table_name="provider_services")
    op.drop_index(op.f("ix_provider_services_category"), table_name="provider_services")
    op.drop_index(op.f("ix_provider_services_api_provider_id"), table_name="provider_services")
    op.drop_table("provider_services")
    op.drop_index(op.f("ix_product_requests_user_id"), table_name="product_requests")
    op.drop_index(op.f("ix_product_requests_title"), table_name="product_requests")
    op.drop_index(op.f("ix_product_requests_status"), table_name="product_requests")
    op.drop_index(op.f("ix_product_requests_normalized_title"), table_name="product_requests")
    op.drop_index(op.f("ix_product_requests_created_at"), table_name="product_requests")
    op.drop_table("product_requests")
    op.drop_index(op.f("ix_number_orders_user_id"), table_name="number_orders")
    op.drop_table("number_orders")
    op.drop_index(op.f("ix_loyalty_events_user_id"), table_name="loyalty_events")
    op.drop_index(op.f("ix_loyalty_events_event_key"), table_name="loyalty_events")
    op.drop_index(op.f("ix_loyalty_events_created_at"), table_name="loyalty_events")
    op.drop_table("loyalty_events")
    op.drop_index(op.f("ix_gift_codes_code"), table_name="gift_codes")
    op.drop_table("gift_codes")
    op.drop_index(op.f("ix_deposit_requests_user_id"), table_name="deposit_requests")
    op.drop_index(op.f("ix_deposit_requests_proof_tx_number"), table_name="deposit_requests")
    op.drop_table("deposit_requests")
    op.drop_index(op.f("ix_coupons_code"), table_name="coupons")
    op.drop_table("coupons")
    op.drop_index(op.f("ix_countries_code"), table_name="countries")
    op.drop_table("countries")
    op.drop_index(op.f("ix_challenge_progress_user_id"), table_name="challenge_progress")
    op.drop_index(op.f("ix_challenge_progress_challenge_id"), table_name="challenge_progress")
    op.drop_table("challenge_progress")
    op.drop_index(op.f("ix_cashback_logs_user_id"), table_name="cashback_logs")
    op.drop_table("cashback_logs")
    op.drop_table("broadcast_logs")
    op.drop_index(op.f("ix_auto_invoices_user_id"), table_name="auto_invoices")
    op.drop_index(op.f("ix_auto_invoices_transaction_ref"), table_name="auto_invoices")
    op.drop_index(op.f("ix_auto_invoices_external_invoice_id"), table_name="auto_invoices")
    op.drop_table("auto_invoices")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_admin_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_abuse_events_user_id"), table_name="abuse_events")
    op.drop_index(op.f("ix_abuse_events_event_type"), table_name="abuse_events")
    op.drop_index(op.f("ix_abuse_events_created_at"), table_name="abuse_events")
    op.drop_table("abuse_events")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("stars_packages")
    op.drop_table("settings")
    op.drop_table("service_pricing")
    op.drop_table("provider_status")
    op.drop_index(op.f("ix_number_services_code"), table_name="number_services")
    op.drop_table("number_services")
    op.drop_table("mandatory_channels")
    op.drop_index(op.f("ix_challenges_status"), table_name="challenges")
    op.drop_index(op.f("ix_challenges_code"), table_name="challenges")
    op.drop_table("challenges")
    op.drop_table("categories")
    op.drop_table("api_providers")
    # ### end Alembic commands ###
